<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<!-- Generated by PHPExcel - http://www.phpexcel.net -->
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <meta name="author" content="Bayu Indra" />
    <style type="text/css">
        html { font-family:Calibri, Arial, Helvetica, sans-serif; font-size:11pt; background-color:white }
        table { border-collapse:collapse; page-break-after:always }
        .gridlines td { border:1px dotted black }
        .gridlines th { border:1px dotted black }
        .b { text-align:center }
        .e { text-align:center }
        .f { text-align:right }
        .inlineStr { text-align:left }
        .n { text-align:right }
        .s { text-align:left }
        td.style0 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri'; font-size:11pt; background-color:white }
        th.style0 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri'; font-size:11pt; background-color:white }
        td.style1 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style1 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style2 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style2 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style3 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:2px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style3 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:2px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style4 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style4 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style5 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:2px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style5 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:2px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style6 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:2px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style6 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:2px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style7 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style7 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style8 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style8 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style9 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#002060; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style9 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#002060; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style10 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:2px solid #000000 !important; font-weight:bold; color:#002060; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style10 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:2px solid #000000 !important; font-weight:bold; color:#002060; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style11 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style11 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style12 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style12 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style13 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style13 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style14 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style14 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style15 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style15 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style16 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style16 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style17 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style17 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style18 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style18 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style19 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style19 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style20 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:2px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style20 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:2px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style21 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style21 { vertical-align:middle; text-align:right; padding-right:0px; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style22 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style22 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style23 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style23 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style24 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:2px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style24 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:2px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style25 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style25 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style26 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style26 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style27 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style27 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style28 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style28 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style29 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:2px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style29 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:2px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style30 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style30 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style31 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style31 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style32 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:1px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style32 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:none #000000; border-right:1px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style33 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style33 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style34 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:1px solid #000000 !important; border-right:2px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style34 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:none #000000; border-left:1px solid #000000 !important; border-right:2px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style35 { vertical-align:bottom; text-align:center; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style35 { vertical-align:bottom; text-align:center; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style36 { vertical-align:bottom; text-align:center; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style36 { vertical-align:bottom; text-align:center; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style37 { vertical-align:bottom; text-align:center; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:1px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style37 { vertical-align:bottom; text-align:center; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:1px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style38 { vertical-align:bottom; text-align:center; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style38 { vertical-align:bottom; text-align:center; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style39 { vertical-align:bottom; text-align:center; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:1px solid #000000 !important; border-right:2px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style39 { vertical-align:bottom; text-align:center; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:1px solid #000000 !important; border-right:2px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style40 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:1px solid #000000 !important; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style40 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:1px solid #000000 !important; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style41 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style41 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style42 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style42 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style43 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:none #000000; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style43 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:none #000000; border-left:1px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style44 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style44 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style45 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:1px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style45 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:1px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style46 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:2px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style46 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:2px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style47 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:2px solid #000000 !important; border-left:2px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:12pt; background-color:#FFFFFF }
        th.style47 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:2px solid #000000 !important; border-left:2px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:12pt; background-color:#FFFFFF }
        td.style48 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:2px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:12pt; background-color:#FFFFFF }
        th.style48 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:2px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:12pt; background-color:#FFFFFF }
        td.style49 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:2px solid #000000 !important; border-left:none #000000; border-right:2px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:12pt; background-color:#FFFFFF }
        th.style49 { vertical-align:middle; text-align:center; border-bottom:none #000000; border-top:2px solid #000000 !important; border-left:none #000000; border-right:2px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:12pt; background-color:#FFFFFF }
        td.style50 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:none #000000; border-left:2px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:12pt; background-color:#FFFFFF }
        th.style50 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:none #000000; border-left:2px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:12pt; background-color:#FFFFFF }
        td.style51 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:12pt; background-color:#FFFFFF }
        th.style51 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:12pt; background-color:#FFFFFF }
        td.style52 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:2px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:12pt; background-color:#FFFFFF }
        th.style52 { vertical-align:middle; text-align:center; border-bottom:2px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:2px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:12pt; background-color:#FFFFFF }
        td.style53 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style53 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style54 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style54 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style55 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:2px solid #000000 !important; border-right:1px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style55 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:2px solid #000000 !important; border-right:1px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style56 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:2px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style56 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:2px solid #000000 !important; border-right:1px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style57 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:2px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style57 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:2px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style58 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:2px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style58 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:2px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style59 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:2px solid #000000 !important; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style59 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:2px solid #000000 !important; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style60 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:2px solid #000000 !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style60 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:2px solid #000000 !important; border-left:none #000000; border-right:none #000000; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style61 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:2px solid #000000 !important; border-left:none #000000; border-right:2px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style61 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:2px solid #000000 !important; border-left:none #000000; border-right:2px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style62 { vertical-align:bottom; text-align:center; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:2px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style62 { vertical-align:bottom; text-align:center; border-bottom:1px solid #000000 !important; border-top:none #000000; border-left:none #000000; border-right:2px solid #000000 !important; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style63 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style63 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style64 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:2px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style64 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:2px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style65 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style65 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style66 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style66 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style67 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style67 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style68 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style68 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style69 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style69 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style70 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style70 { vertical-align:middle; text-align:left; padding-left:9px; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style71 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style71 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style72 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:2px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style72 { vertical-align:bottom; text-align:center; border-bottom:none #000000; border-top:1px solid #000000 !important; border-left:none #000000; border-right:2px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style73 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:2px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style73 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:2px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style74 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style74 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style75 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style75 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:none #000000; border-right:1px solid #000000 !important; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style76 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        th.style76 { vertical-align:middle; text-align:center; border-bottom:1px solid #000000 !important; border-top:1px solid #000000 !important; border-left:1px solid #000000 !important; border-right:none #000000; font-weight:bold; color:#000000; font-family:'Calibri Light'; font-size:10pt; background-color:#FFFFFF }
        td.style77 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri'; font-size:11pt; background-color:white }
        th.style77 { vertical-align:bottom; border-bottom:none #000000; border-top:none #000000; border-left:2px solid #000000 !important; border-right:none #000000; color:#000000; font-family:'Calibri'; font-size:11pt; background-color:white }
        table.sheet0 col.col0 { width:43.37777728pt }
        table.sheet0 col.col1 { width:42pt }
        table.sheet0 col.col2 { width:42pt }
        table.sheet0 col.col3 { width:42pt }
        table.sheet0 col.col4 { width:42pt }
        table.sheet0 col.col5 { width:42pt }
        table.sheet0 col.col6 { width:42pt }
        table.sheet0 col.col7 { width:42pt }
        table.sheet0 col.col8 { width:140.97777616pt }
        table.sheet0 col.col9 { width:111.15555428pt }
        table.sheet0 tr { height:15pt }
        table.sheet0 tr.row1 { height:15pt }
        table.sheet0 tr.row2 { height:15.75pt }
        table.sheet0 tr.row15 { height:15pt }
        table.sheet0 tr.row20 { height:15.75pt }
    </style>
</head>

<body>
<style>
    @page { left-margin: 0.7in; right-margin: 0.7in; top-margin: 0.75in; bottom-margin: 0.75in; }
    body { left-margin: 0.7in; right-margin: 0.7in; top-margin: 0.75in; bottom-margin: 0.75in; }
</style>
<table border="0" cellpadding="0" cellspacing="0" id="sheet0" class="sheet0 gridlines">
    <col class="col0">
    <col class="col1">
    <col class="col2">
    <col class="col3">
    <col class="col4">
    <col class="col5">
    <col class="col6">
    <col class="col7">
    <col class="col8">
    <col class="col9">
    <tbody>
    <tr class="row0">
        <td class="column0 style47 s style52" colspan="9" rowspan="2">
            <img width=150 height=auto style="position: absolute; left: 12px; top: 12px;" src="{{ URL::asset('assets/images/image001.png') }}">
            SURAT JALAN</td>
        <td class="column9 style77 null"></td>
    </tr>
    <tr class="row1">
        <td class="column9 style77 null"></td>
    </tr>
    <tr class="row2">
        <td class="column0 style59 null style61" colspan="9"></td>
        <td class="column9 style77 null"></td>
    </tr>

    <tr class="row3">
        <td class="column0 style64 s style54" colspan="2">FROM.</td>
        <td class="column2 style53 s style54" colspan="3">{{ $header->fromWarehouse->name }}</td>
        <td class="column5 style4 null"></td>
        <td class="column6 style53 s style54" colspan="2">GR. NO.</td>
        <td class="column8 style5 s">{{ !empty($header->item_receipt_id) ? $header->item_receipt_header->code : '--' }}</td>
        <td class="column9 style77 null"></td>
    </tr>
    <tr class="row4">
        <td class="column0 style64 s style54" colspan="2">TO.</td>
        <td class="column2 style53 s style54" colspan="3">{{ $header->toWarehouse->name }}</td>
        <td class="column5 style4 null"></td>
        <td class="column6 style53 s style54" colspan="2">DATE OF GR.</td>
        <td class="column8 style6 s">{{ !empty($header->item_receipt_id) ? $header->item_receipt_header->date_string : '--' }}</td>
        <td class="column9 style77 null"></td>
    </tr>
    <tr class="row5">
        <td class="column0 style64 s style54" colspan="2">DELIVERY NO.</td>
        <td class="column2 style65 n style67" colspan="3">{{ $header->code }}</td>
        <td class="column5 style7 null"></td>
        <td class="column6 style53 s style54" colspan="2">PR. NO.</td>
        <td class="column8 style5 s">{{ !empty($header->item_receipt_id) ? $header->item_receipt_header->purchase_order_header->purchase_request_header->code : '--' }}</td>
        <td class="column9 style77 null"></td>
    </tr>
    <tr class="row6">
        <td class="column0 style64 s style54" colspan="2">DATE.</td>
        <td class="column2 style53 s style54" colspan="3">{{ $header->date_string }}</td>
        <td class="column5 style8 null"></td>
        <td class="column6 style53 s style54" colspan="2">DATE OF PR.</td>
        <td class="column8 style5 s">{{ !empty($header->item_receipt_id) ? $header->item_receipt_header->purchase_order_header->purchase_request_header->date_string : '--' }}</td>
        <td class="column9 style77 null"></td>
    </tr>
    <tr class="row7">
        <td class="column0 style64 s style54" colspan="2">UNIT TYPE.</td>
        <td class="column2 style53 s style54" colspan="3">{{ !empty($header->machinery_id) ? $header->machinery->type : '--' }}</td>
        <td class="column5 style7 null"></td>
        <td class="column6 style53 s style54" colspan="2">MR NO.</td>
        <td class="column8 style5 s">{{ !empty($header->item_receipt_id) ? $header->item_receipt_header->purchase_order_header->purchase_request_header->material_request_header->code : '--' }}</td>
        <td class="column9 style77 null"></td>
    </tr>
    <tr class="row8">
        <td class="column0 style64 s style54" colspan="2">UNIT NO.</td>
        <td class="column2 style68 s style70" colspan="3">{{ !empty($header->machinery_id) ? $header->machinery->code : '--' }}</td>
        <td class="column5 style2 null"></td>
        <td class="column6 style53 s style54" colspan="2">DATE OF MR.</td>
        <td class="column8 style5 s">{{ !empty($header->item_receipt_id) ? $header->item_receipt_header->purchase_order_header->purchase_request_header->material_request_header->date_string : '--' }}</td>
        <td class="column9 style77 null"></td>
    </tr>
    <tr class="row8">
        <td class="column0 style64 s style54" colspan="2">PRIORITY.</td>
        <td class="column2 style68 s style70" colspan="3">{{ !empty($header->item_receipt_id) ? $header->item_receipt_header->purchase_order_header->purchase_request_header->priority : '--' }}</td>
        <td class="column5 style2 null"></td>
        <td class="column6 style53 s style54" colspan="2">NO PO.</td>
        <td class="column8 style5 s">{{ !empty($header->item_receipt_id) ? $header->item_receipt_header->purchase_order_header->code : '--' }}</td>
        <td class="column9 style77 null"></td>
    </tr>
    <tr class="row8">
        <td class="column0 style64 s style54" colspan="2">SUPPLIER</td>
        <td class="column2 style68 s style70" colspan="3">{{ !empty($header->item_receipt_id) ? $header->item_receipt_header->purchase_order_header->supplier->name : '--' }}</td>
        <td class="column5 style2 null"></td>
        <td class="column6 style53 s style54" colspan="2">DATE OF PO.</td>
        <td class="column8 style5 s">{{ !empty($header->item_receipt_id) ? $header->item_receipt_header->purchase_order_header->purchase_request_header->date_string : '--' }}</td>
        <td class="column9 style77 null"></td>
    </tr>
    <tr class="row9">
        <td class="column0 style35 null style62" colspan="9"></td>
        <td class="column9 style77 null"></td>
    </tr>
    <tr class="row10">
        <td class="column0 style55 s">NO.</td>
        <td class="column1 style76 s style75" colspan="2">PART NUMBER</td>
        <td class="column3 style76 s style75" colspan="3">PART NAME</td>
        <td class="column6 style76 s style75" colspan="2">QTY</td>
        <td class="column8 style57 s">REMARKS</td>
        <td class="column9 style77 null"></td>
    </tr>

    @php( $idx = 1 )
    @foreach($header->delivery_order_details as $detail)
        <tr class="row11">
            <td class="column0 style56 n">{{ $idx }}</td>
            <td class="column1 style12 s style13" colspan="2">{{ $detail->item->code }}</td>
            <td class="column3 style14 s style16" colspan="3">{{ $detail->item->name }}</td>
            <td class="column6 style11 n">{{ $detail->quantity }}</td>
            <td class="column7 style11 s">{{ $detail->item->uom }}</td>
            <td class="column8 style58 s">{{ $detail->remark ?? '--' }}</td>
            <td class="column9 style77 null"></td>
        </tr>
    @endforeach

    <tr class="row12">
        <td class="column0 style17 null"></td>
        <td class="column1 style18 null"></td>
        <td class="column2 style18 null"></td>
        <td class="column3 style19 null"></td>
        <td class="column4 style19 null"></td>
        <td class="column5 style19 null"></td>
        <td class="column6 style19 null"></td>
        <td class="column7 style19 null"></td>
        <td class="column8 style20 null"></td>
        <td class="column9 style77 null"></td>
    </tr>
    <tr class="row13">
        <td class="column0 style17 null"></td>
        <td class="column1 style18 null"></td>
        <td class="column2 style19 null"></td>
        <td class="column3 style19 null"></td>
        <td class="column4 style19 null"></td>
        <td class="column5 style19 null"></td>
        <td class="column6 style21 null"></td>
        <td class="column7 style19 null"></td>
        <td class="column8 style20 null"></td>
        <td class="column9 style77 null"></td>
    </tr>
    <tr class="row14">
        <td class="column0 style73 s style75" colspan="3">NOTE</td>
        <td class="column3 style22 s style24" colspan="6">{{ $header->remark ?? '--' }}</td>
        <td class="column9 style77 null"></td>
    </tr>
    <tr class="row15">
        <td class="column0 style1 null"></td>
        <td class="column1 style2 null"></td>
        <td class="column2 style2 null"></td>
        <td class="column3 style2 null"></td>
        <td class="column4 style2 null"></td>
        <td class="column5 style2 null"></td>
        <td class="column6 style2 null"></td>
        <td class="column7 style2 null"></td>
        <td class="column8 style3 null"></td>
        <td class="column9 style77 null"></td>
    </tr>
    <tr class="row16">
        <td class="column0 style73 s style75" colspan="3">Pengirim</td>
        {{--<td class="column3 style76 s style75" colspan="2" style="border-right: none !important; border-top: none !important; border-bottom: none !important;"></td>--}}
        {{--<td class="column5 style76 s style75" colspan="3" style="border-left: none !important; border-top: none !important; border-bottom: none !important;"></td>--}}
        {{--<td class="column8 style57 s">Ekspedisi</td>--}}
        <td class="column3 style76 s style75" colspan="2">Quality Control</td>
        <td class="column5 style76 s style75" colspan="3">Penerima 1</td>
        <td class="column8 style57 s">Penerima 2</td>
        <td class="column9 style77 null"></td>
    </tr>
    <tr class="row17">
        <td class="column0 style25 s style37" colspan="3" rowspan="3"></td>
        {{--<td class="column3 style28 s style37" colspan="2" rowspan="3" style="border-right: none !important; border-bottom: none !important; border-top: none !important;"></td>--}}
        {{--<td class="column5 style28 s style37" colspan="3" rowspan="3" style="border-left: none !important; border-bottom: none !important; border-top: none !important;"></td>--}}
        <td class="column3 style28 s style37" colspan="2" rowspan="3"></td>
        <td class="column5 style28 s style37" colspan="3" rowspan="3"></td>
        <td class="column8 style29 s style39" rowspan="3"></td>
        <td class="column9 style77 null"></td>
    </tr>
    <tr class="row18">
        <td class="column9 style77 null"></td>
    </tr>
    <tr class="row19">
        <td class="column9 style77 null"></td>
    </tr>
    <tr class="row20">
        <td class="column0 style40 s style41" colspan="3"></td>
        {{--<td class="column3 style42 s style41" colspan="2" style="border-right: none !important; border-top: none !important;"></td>--}}
        {{--<td class="column5 style43 s style45" colspan="3" style="border-left: none !important; border-top: none !important;"></td>--}}
        <td class="column3 style42 s style41" colspan="2"></td>
        <td class="column5 style43 s style45" colspan="3"></td>
        <td class="column8 style46 s"></td>
        <td class="column9 style77 null"></td>
    </tr>
    </tbody>
</table>
</body>
</html>
